### Slicing And Copying

In [ ]:
import numpy as np 

np.random.seed(0) # This will prevent the random numbers to change each time we run the code again
np_rand = np.random.random((3,3))
print(np_rand)

# If we want 2 rows and 3 colls
print("-------------------------------------------------")
print(np_rand[0:2, 0:2])

# Copy arrays in case we want to take out and some manipulate some data
# from the original array without affecting the values in the original array
print("-------------------------------------------------")
copyRand = np.copy(np_rand[0:2, 0:2]) 

print(copyRand)

## Inserting, Append And Delete Numpy

In [32]:
# INSERT
# With 'insert' method, you can specify where you want to add new elements.
# ------------------------------------------------------------------------------------------------------------
# APPEND
# The 'append' method is for concatenating new elements. So the are added AFTER the original array elements
# If the 'axis' parameter is not used, the output will be 1D array
# If the axis parameter was used, the elements MUST have the SAME SHAPE as the original array
# If the 'axis' parameter is 1, then the added elements must have the CORRECT SHAPE with the original array
#-------------------------------------------------------------------------------------------------------------
# DELETE
# You can delete elements from a 1D Numpy array using 'delete' functions
# You can delete elements from a higher Numpy array using delete function by specifying the 'axis' parameter

#### --> Inserting

In [9]:
import numpy as np

In [47]:
np_arr = np.array([[1,2],[6,8]])
print(np_arr)

# Insert values
np_arr = np.insert(arr=np_arr, obj=1, values=[5,78], axis=0) # axis = 0 will insert in the rows. obj is the position index
print(np_arr)


[[1 2]
 [6 8]]
[[ 1  2]
 [ 5 78]
 [ 6  8]]


### -->Appending

In [56]:
np_arr_append = np.append(arr=np_arr, values=[3,5]) # Append converts to a 1D array.
print(np_arr_append)

# To covert to a 2D array, you need to add a 2D array values and specify the axis
np_arr_append = np.append(arr=np_arr, values = [[3,5], [54,25]], axis=0)
print(np_arr_append)

[ 1  2  5 78  6  8  3  5]
[[ 1  2]
 [ 5 78]
 [ 6  8]
 [ 3  5]
 [54 25]]


### --> Deleting 

In [57]:
np_arr = np.delete(arr=np_arr, obj=0, axis=0) # Specify the index based on the axis
print(np_arr)

[[ 5 78]
 [ 6  8]]


## Array Logical Indexing

In [8]:
# In case you want to select an array based on a certain condition

np_arrLogic = np.array([[1,3,5], [3,2,4],[1,3,8]])
np_arr_cond = np_arrLogic[np_arrLogic >= 2]
print(np_arr_cond) # Return values greater than 3 in a 1D array
print(np_arrLogic > 3) # This will return boolean values in a 2D array

[3 5 3 2 4 3 8]
[[False False  True]
 [False False  True]
 [False False  True]]


## Broadcasting

In [11]:
# Broadcasting is how Numpy performs arithmethic operation btw arrays with DIFFERENT shapes
# This is done by broadcating the SMALLER
# This is faster than 'for loops'. It saves memory 
# --> One of the dimension is one
# --> Trailing dimentions must match. i,e 


arr = np.array([[2,3],[4,5],[6,8]])
brc_arr = arr * 5 # This multiplies each element in the array by 5
print(brc_arr)

[[10 15]
 [20 25]
 [30 40]]
