# Importing Script

In [ ]:
# When your projects gets bigger, it's better to refactor it into different modules
# To use this file, use import keyword. E.g import module1
# In case you only need a function or two from the module, just import only those instead of the whole file. 
# E.g from module1 import function1, function2
# You can rename the module using as keword. E.g import module1 as m1.
# You can combine the last two points above. E.g from module1 import function1 as F1, function2 as F2

## --> Standard Libraries

### * Numpy

In [ ]:
# Used to complex mathematical operations. Used by data scientists, machine learning
# Main data structure is arrays. A multi-dimensional array with the same data type.
# Can be created using Numpy functions or by converting Python lists to Numpy arrays
# Standard practice is to give the module an alias 'np' after importing
# Convert a Python list into Numpy array using 'np.asarray' function. E.g
'''
    import numpy as np
    list = [1,2,3,6]
    npArray = np.asarray(list)
'''
# We can get the SHAPE and the DATA TYPE of the array element ushig 'shape' and 'dtype' attributes. E.g
'''
    print(npArray.shape)
    print(npArray.dtype)
'''
# You can also FORCE the data type of the Numpy array. E.g
'''
    npArray = np.array(mylist, dtype = np.int64)
    print(npArray.shape)
    print(npArray.dtype)
'''
# Numpy has its own data types whis is different from Python ones. E.g int is different from int64
# Other array functions are : 
'''
    np.zeros((2,5))
    np.ones((3,6))
    np.arange((6)) # similar to range funtion
    np.linespace(0,10,2)
    np.random.random((5,5))
'''


In [35]:
import numpy as np

my_list = [1,2,3,4,5,6,7,8,9,10,11,12,13]
npArray = np.asarray(my_list)

print(npArray)
print(npArray.shape)
print(npArray.dtype)
print(npArray.max())
print(npArray.sum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
(13,)
int32
13
91


In [46]:
numpyZeros = np.zeros((2,3), dtype=int)
numpyOnes = np.ones((3,6))
numpyRange = np.arange(start = 2, step = 2, stop = 20) # similar to range funtion
linespace = np.linspace(start = 2, stop = 20, num = 10)
numpyRandom = np.random.random((2,5))


print(numpyZeros)
print(numpyOnes)
print(numpyRange)
print(linespace)
print(numpyRandom)


[[0 0 0]
 [0 0 0]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[ 2  4  6  8 10 12 14 16 18]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[[0.52260463 0.37637308 0.26047399 0.40588939 0.41887875]
 [0.81433214 0.67700163 0.00200424 0.72969357 0.57881315]]


#### --> Reshaping, Accessing And Modifying Nympy

In [50]:
# Can reshape using 'reshape' function 
# You can access specific element in a Numpy array the same way with Python list in case of 1D arrays, using the index

# ---------------------------------------------------------------------------------------------------------------------

# Accessing various dimentions of array

myArray2 = np.arange(20)
print(myArray2)

myArray2_reshaped = np.reshape(myArray2,(5,4), order= 'F') # The product of these figures must be eqaul to the range in myArray2
                                                           # The order rearrange the row first to collumn first
print(myArray2_reshaped)
print(myArray2_reshaped[1,2]) # Accessing individual data
# 


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
11


In [ ]:
# SLICING AND COPYING
