## Pandas Data Frame

In [ ]:
# Dataframes are two-dimensional data structure
# Can be imagined as a combination of many series
# A dictionary for Series object
# Each column of the DataFrame is a Series object
# We can also create a dataFrame by reading a csv file. Google kaggle to get dataset info. **IMPORTANT**)
# ---------------------------------------------------------------------------------------------------------
# ATTRIBUTES
# * Shape
# * ndim
# * size
# * values
# * index
# * columns

In [3]:
import pandas as pd
import numpy as np

# Data from a dictionary. All arrays must be of the same length
di = {"tweets" : ["Tweeter has changed her logo", "Elon Musk is confused", "Making money"], "Users" : ["Seyi", "Tunde", "Sola"],
      "Verified" : [True, False, False]}
df_di = pd.DataFrame(di)
print(df_di)

                         tweets  Users  Verified
0  Tweeter has changed her logo   Seyi      True
1         Elon Musk is confused  Tunde     False
2                  Making money   Sola     False


In [11]:
# If created from pandas Series, they may not be of the same length. In the place of null value, NaN is used

diSeries = {"tweets" : pd.Series(["Tweeter has changed her logo", "Elon Musk is confused", "Making money"]), 
       "Users" : pd.Series(["Seyi", "Tunde", "Sola"]),
      "Verified" : pd.Series([True, False, False])}
df_diSeries = pd.DataFrame(diSeries)
print(df_diSeries)

                         tweets  Users  Verified
0  Tweeter has changed her logo   Seyi      True
1         Elon Musk is confused  Tunde     False
2                  Making money   Sola     False


In [14]:
# From a dict of ndarrays/list 
# '0' will be used as the column name if we we didnt specify the column parameter

myList = [1,25,54,10,54]
dfList = pd.DataFrame(myList, columns= ["Figures"])
print(dfList)

   Figures
0        1
1       25
2       54
3       10
4       54


In [3]:
# From a list of dictionary
# key names should be the same else another collumn is created
# Each element is a row
list_dic = [{"a" : 2, "c" : 4.5}, {"a" : 4, "y" : 12}]
df_list_dic = pd.DataFrame(list_dic)
print(df_list_dic)

   a    c     y
0  2  4.5   NaN
1  4  NaN  12.0


In [5]:
# 2-D numpy.ndarray
np_arr = 4.5 * np.ones((3,3))
np_dataframe = pd.DataFrame(np_arr)
print(np_arr)


[[4.5 4.5 4.5]
 [4.5 4.5 4.5]
 [4.5 4.5 4.5]]


In [6]:
# From another dataframe
# Useful if we want to perform some operations on a dataframe and store it in another dataframe

another_df = pd.DataFrame(np_dataframe)
print(another_df)

     0    1    2
0  4.5  4.5  4.5
1  4.5  4.5  4.5
2  4.5  4.5  4.5


In [4]:
# From a csv file

pd_csv = pd.read_csv('Datasets/melb_data.csv')
print(pd_csv.head()) # using .head() method prints first 5 elements by default

       Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0     